/**
 * Cooperative generation lock.
 *
 * A single project must not be generated by two processes at once (VS Code and a
 * CI run, or two windows). The lock is a JSON file under the project state root.
 * A lock left behind by a crashed process is detected as stale — either the
 * owning PID is gone or the timestamp is older than {@link STALE_LOCK_MS} — and
 * may be taken over. Every mutation is path-checked against the project root.
 */
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { assertPathInside } from './pathSecurity';

export interface LockInfo {
  pid: number;
  actor: string;
  hostname: string;
  createdAt: string;
}

export const STALE_LOCK_MS = 10 * 60 * 1000;

export function lockPath(projectRoot: string): string {
  return assertPathInside(projectRoot, path.join(projectRoot, '.aem-catalog', 'generation.lock'), 'Lock file');
}

export function readLock(projectRoot: string): LockInfo | null {
  const file = lockPath(projectRoot);
  if (!fs.existsSync(file)) return null;
  try {
    const parsed = JSON.parse(fs.readFileSync(file, 'utf-8')) as Partial<LockInfo>;
    if (typeof parsed.pid !== 'number' || typeof parsed.createdAt !== 'string') return null;
    return {
      pid: parsed.pid,
      actor: String(parsed.actor ?? 'unknown'),
      hostname: String(parsed.hostname ?? ''),
      createdAt: parsed.createdAt,
    };
  } catch {
    return null;
  }
}

/** A lock is stale when its owning process is gone or it has outlived the TTL. */
export function isLockStale(lock: LockInfo, now = new Date()): boolean {
  const age = now.getTime() - new Date(lock.createdAt).getTime();
  if (!Number.isFinite(age) || age > STALE_LOCK_MS) return true;
  if (lock.hostname && lock.hostname !== os.hostname()) return false;
  return !isProcessAlive(lock.pid);
}

/**
 * Acquire the lock, returning a release function. Throws if a live lock is held
 * by another process. A stale lock is taken over transparently.
 */
export function acquireLock(projectRoot: string, actor: string, now = new Date()): () => void {
  const file = lockPath(projectRoot);
  fs.mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 });
  const existing = readLock(projectRoot);
  if (existing && existing.pid !== process.pid && !isLockStale(existing, now)) {
    throw new Error(
      `Another generation is in progress (pid ${existing.pid}, ${existing.actor}, started ${existing.createdAt}). ` +
        'Wait for it to finish, or clear the stale lock if that process is gone.',
    );
  }
  const info: LockInfo = {
    pid: process.pid,
    actor,
    hostname: os.hostname(),
    createdAt: now.toISOString(),
  };
  fs.writeFileSync(file, `${JSON.stringify(info, null, 2)}\n`, { encoding: 'utf-8', mode: 0o600 });
  let released = false;
  return () => {
    if (released) return;
    released = true;
    const current = readLock(projectRoot);
    if (current && current.pid === process.pid && fs.existsSync(file)) fs.unlinkSync(file);
  };
}

/** Remove a stale lock. Refuses to clear a lock still owned by a live process. */
export function clearStaleLock(projectRoot: string, now = new Date()): boolean {
  const lock = readLock(projectRoot);
  if (!lock) return false;
  if (!isLockStale(lock, now)) {
    throw new Error(`The generation lock is held by a live process (pid ${lock.pid}); refusing to clear it.`);
  }
  const file = lockPath(projectRoot);
  if (fs.existsSync(file)) fs.unlinkSync(file);
  return true;
}

function isProcessAlive(pid: number): boolean {
  if (!Number.isInteger(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    // ESRCH = no such process (dead); EPERM = alive but not ours (still alive).
    return (error as NodeJS.ErrnoException).code === 'EPERM';
  }
}
